import { FileText, Download, Sparkles } from 'lucide-react'
import { PageHeader, Card, CardHead, ToneBadge } from '@/components/kit'
import { reports } from '@/lib/data'

export default function ReportsPage() {
  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        icon={<FileText className="h-5 w-5" />}
        title="Reports"
        desc="AI-generated reports tailored to each audience — from daily operations to executive summaries — refreshed automatically."
        actions={
          <button className="inline-flex items-center gap-2 rounded-lg bg-ai px-3 py-2 text-sm font-medium text-ai-foreground transition hover:opacity-90">
            <Sparkles className="h-4 w-4" />
            Generate report
          </button>
        }
      />

      <Card className="border-ai/30 bg-ai/5">
        <CardHead title="Today's Executive Summary" desc="Auto-generated by the Executive Agent · 06:00 UTC" />
        <div className="space-y-3 px-5 pb-5 text-sm text-muted-foreground">
          <p>
            Platform health is <span className="text-healthy">98.4%</span> with one active P1 incident. Document upload
            failures (INC-1042) are the day's dominant issue, caused by deploy #1482 and putting an estimated{' '}
            <span className="text-foreground">$12.4k MRR</span> at risk. A rollback is drafted and awaiting approval.
          </p>
          <p>
            Growth remains strong at <span className="text-healthy">+9% WAU week-over-week</span>, led by the EU sharing
            feature. Recommended priority for engineering today: ship the storage fix and expand the auth connection pool.
          </p>
        </div>
      </Card>

      <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
        {reports.map((r) => (
          <Card key={r.title} className="flex flex-col p-5">
            <div className="flex items-start justify-between">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg border border-border/70 bg-card text-intel">
                <FileText className="h-5 w-5" />
              </div>
              <ToneBadge tone={r.tone}>{r.freq}</ToneBadge>
            </div>
            <h3 className="mt-4 text-sm font-semibold text-foreground">{r.title}</h3>
            <p className="mt-1 flex-1 text-xs text-muted-foreground">{r.desc}</p>
            <div className="mt-4 flex items-center gap-2">
              <button className="inline-flex flex-1 items-center justify-center gap-2 rounded-lg border border-border/70 bg-card px-3 py-2 text-xs font-medium text-foreground transition hover:bg-muted">
                <Download className="h-3.5 w-3.5" />
                Export PDF
              </button>
              <button className="inline-flex items-center justify-center gap-2 rounded-lg border border-ai/25 bg-ai/10 px-3 py-2 text-xs font-medium text-ai transition hover:bg-ai/20">
                <Sparkles className="h-3.5 w-3.5" />
                Regenerate
              </button>
            </div>
          </Card>
        ))}
      </div>
    </div>
  )
}
