import { FileText, Sparkles } from 'lucide-react'
import { PageHeader, Card, CardHead } from '@/components/kit'

export default function ReportsPage() {
  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        icon={<FileText className="h-5 w-5" />}
        title="Reports"
        desc="AI-generated reports tailored to each audience — from daily operations to executive summaries — refreshed automatically."
        actions={
          <button className="inline-flex items-center gap-2 rounded-lg bg-ai px-3 py-2 text-sm font-medium text-ai-foreground transition hover:opacity-90">
            <Sparkles className="h-4 w-4" />
            Generate report
          </button>
        }
      />

      <Card className="border-ai/30 bg-ai/5">
        <CardHead title="Executive Summary" desc="Auto-generated by the Executive Agent" />
        <div className="space-y-3 px-5 pb-5 text-sm text-muted-foreground">
          <p>
            Reports will be generated automatically once the platform has accumulated sufficient data.
            Connect your data sources and run the PAAQ SDK to start generating AI-powered executive summaries.
          </p>
        </div>
      </Card>

      <Card>
        <CardHead title="Report Templates" desc="Available report types" />
        <div className="p-10 text-center">
          <FileText className="mx-auto mb-3 h-8 w-8 text-muted-foreground opacity-20" />
          <p className="text-sm text-muted-foreground">No reports generated yet.</p>
        </div>
      </Card>
    </div>
  )
}
